# Generated by Django 6.0.3 on 2026-03-13 10:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='YouthProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='data de nascimento')),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro'), ('N', 'Prefiro não dizer')], max_length=1, verbose_name='sexo')),
                ('localidade', models.CharField(blank=True, max_length=255, verbose_name='localidade')),
                ('situacao_atual', models.CharField(choices=[('EMP', 'Empregado'), ('DES', 'Desempregado'), ('PEM', 'Primeiro Emprego')], default='DES', max_length=3, verbose_name='situação atual')),
                ('disponibilidade', models.CharField(choices=[('SIM', 'Sim'), ('NAO', 'Não'), ('EM_BREVE', 'Em breve')], default='SIM', max_length=10, verbose_name='disponibilidade imediata')),
                ('interesse_setorial', models.CharField(blank=True, choices=[('AGR', 'Agricultura'), ('TUR', 'Turismo'), ('TIC', 'Tecnologias de Informação'), ('IND', 'Indústria'), ('SER', 'Serviços'), ('ENE', 'Energias Renováveis'), ('ADM', 'Administração'), ('SAU', 'Saúde'), ('EDU', 'Educação'), ('CON', 'Construção'), ('ELE', 'Eletricidade'), ('CAN', 'Canalização'), ('INF', 'Informática'), ('OUT', 'Outra')], max_length=3, verbose_name='setor de interesse')),
                ('preferencia_oportunidade', models.CharField(choices=[('EST', 'Estágio'), ('EMP', 'Emprego'), ('FOR', 'Formação de Curta Duração'), ('EMPRE', 'Empreendedorismo')], default='EMP', max_length=5, verbose_name='preferência de oportunidade')),
                ('sobre', models.TextField(blank=True, help_text='Breve descrição sobre ti', verbose_name='sobre mim')),
                ('completo', models.BooleanField(default=False, verbose_name='perfil completo')),
                ('validado', models.BooleanField(default=False, verbose_name='validado')),
                ('visivel', models.BooleanField(default=True, verbose_name='visível para empresas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('wizard_step', models.IntegerField(default=1, verbose_name='passo do wizard')),
                ('wizard_data', models.JSONField(blank=True, default=dict, verbose_name='dados temporários do wizard')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='youth_profile', to=settings.AUTH_USER_MODEL, verbose_name='utilizador')),
            ],
            options={
                'verbose_name': 'perfil de jovem',
                'verbose_name_plural': 'perfis de jovens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entidade', models.CharField(max_length=255, verbose_name='entidade/empresa')),
                ('cargo', models.CharField(max_length=255, verbose_name='cargo/função')),
                ('inicio', models.DateField(verbose_name='data de início')),
                ('fim', models.DateField(blank=True, null=True, verbose_name='data de fim')),
                ('atual', models.BooleanField(default=False, verbose_name='trabalho atual')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição das atividades')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='profiles.youthprofile', verbose_name='perfil')),
            ],
            options={
                'verbose_name': 'experiência',
                'verbose_name_plural': 'experiências',
                'ordering': ['-inicio'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('BAS', 'Básico'), ('SEC', 'Secundário'), ('TEC', 'Técnico'), ('SUP', 'Superior')], max_length=3, verbose_name='nível')),
                ('area_formacao', models.CharField(choices=[('AGR', 'Agricultura'), ('TUR', 'Turismo'), ('TIC', 'Tecnologias de Informação'), ('IND', 'Indústria'), ('SER', 'Serviços'), ('ENE', 'Energias Renováveis'), ('ADM', 'Administração'), ('SAU', 'Saúde'), ('EDU', 'Educação'), ('CON', 'Construção'), ('ELE', 'Eletricidade'), ('CAN', 'Canalização'), ('INF', 'Informática'), ('OUT', 'Outra')], max_length=3, verbose_name='área de formação')),
                ('instituicao', models.CharField(max_length=255, verbose_name='instituição')),
                ('ano', models.IntegerField(blank=True, null=True, verbose_name='ano de conclusão')),
                ('curso', models.CharField(blank=True, max_length=255, verbose_name='curso/especialidade')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='profiles.youthprofile', verbose_name='perfil')),
            ],
            options={
                'verbose_name': 'formação',
                'verbose_name_plural': 'formações',
                'ordering': ['-ano'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CV', 'Curriculum Vitae'), ('CERT', 'Certificado'), ('BI', 'Bilhete de Identidade'), ('OUTRO', 'Outro')], max_length=10, verbose_name='tipo')),
                ('nome', models.CharField(max_length=255, verbose_name='nome do documento')),
                ('arquivo', models.FileField(upload_to='documents/%Y/%m/', verbose_name='arquivo')),
                ('verificado', models.BooleanField(default=False, verbose_name='verificado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='enviado em')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='profiles.youthprofile', verbose_name='perfil')),
            ],
            options={
                'verbose_name': 'documento',
                'verbose_name_plural': 'documentos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='YouthSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.IntegerField(choices=[(1, 'Básico'), (2, 'Intermédio'), (3, 'Avançado'), (4, 'Especialista')], default=1, verbose_name='nível')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='youth_skills', to='profiles.youthprofile', verbose_name='perfil')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.skill', verbose_name='skill')),
            ],
            options={
                'verbose_name': 'skill do jovem',
                'verbose_name_plural': 'skills dos jovens',
                'unique_together': {('profile', 'skill')},
            },
        ),
    ]
