# Generated by Django 6.0.3 on 2026-03-13 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='youthprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='youth_avatars/', verbose_name='foto de perfil'),
        ),
    ]
