# Generated by Django 6.0.3 on 2026-03-16 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_youthprofile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='youthprofile',
            name='consentimento_email',
            field=models.BooleanField(default=False, verbose_name='consentimento para contacto por Email'),
        ),
        migrations.AddField(
            model_name='youthprofile',
            name='consentimento_sms',
            field=models.BooleanField(default=False, verbose_name='consentimento para contacto por SMS'),
        ),
        migrations.AddField(
            model_name='youthprofile',
            name='consentimento_whatsapp',
            field=models.BooleanField(default=False, verbose_name='consentimento para contacto por WhatsApp'),
        ),
        migrations.AddField(
            model_name='youthprofile',
            name='contacto_alternativo',
            field=models.CharField(blank=True, max_length=255, verbose_name='contacto alternativo'),
        ),
    ]
