# Generated by Django 6.0.3 on 2026-03-16 12:28

from django.db import migrations, models
import json


def wrap_interesse_setorial(apps, schema_editor):
    YouthProfile = apps.get_model('profiles', 'YouthProfile')
    for profile in YouthProfile.objects.all():
        val = profile.interesse_setorial
        if val in (None, ''):
            profile.interesse_setorial = '[]'
        else:
            try:
                parsed = json.loads(val)
                if isinstance(parsed, list):
                    profile.interesse_setorial = json.dumps(parsed)
                elif isinstance(parsed, str):
                    profile.interesse_setorial = json.dumps([parsed])
                else:
                    profile.interesse_setorial = json.dumps([str(parsed)])
            except Exception:
                profile.interesse_setorial = json.dumps([val])
        profile.save(update_fields=['interesse_setorial'])


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_youthprofile_consentimento_email_and_more'),
    ]

    operations = [
        migrations.RunPython(wrap_interesse_setorial, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='youthprofile',
            name='interesse_setorial',
            field=models.JSONField(blank=True, default=list, verbose_name='setores de interesse'),
        ),
    ]
