# Generated by Django 6.0.3 on 2026-03-13 10:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=3, unique=True, verbose_name='código')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
            ],
            options={
                'verbose_name': 'distrito',
                'verbose_name_plural': 'distritos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(max_length=100, unique=True, verbose_name='chave')),
                ('valor', models.TextField(verbose_name='valor')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
            ],
            options={
                'verbose_name': 'configuração',
                'verbose_name_plural': 'configurações',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('tipo', models.CharField(choices=[('TEC', 'Técnica'), ('TRA', 'Transversal')], default='TEC', max_length=3, verbose_name='tipo')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
            ],
            options={
                'verbose_name': 'skill',
                'verbose_name_plural': 'skills',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(max_length=255, verbose_name='ação')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='dados')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='endereço IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='data/hora')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='utilizador')),
            ],
            options={
                'verbose_name': 'log de auditoria',
                'verbose_name_plural': 'logs de auditoria',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='título')),
                ('mensagem', models.TextField(verbose_name='mensagem')),
                ('tipo', models.CharField(choices=[('INFO', 'Informação'), ('SUCESSO', 'Sucesso'), ('ALERTA', 'Alerta'), ('ERRO', 'Erro')], default='INFO', max_length=10, verbose_name='tipo')),
                ('lida', models.BooleanField(default=False, verbose_name='lida')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='utilizador')),
            ],
            options={
                'verbose_name': 'notificação',
                'verbose_name_plural': 'notificações',
                'ordering': ['-created_at'],
            },
        ),
    ]
