# Generated by Django 6.0.3 on 2026-03-16 13:44

from django.db import migrations, models


def set_existing_skills_approved(apps, schema_editor):
    Skill = apps.get_model('core', 'Skill')
    Skill.objects.filter(aprovada=False).update(aprovada=True)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_populate_districts'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='aprovada',
            field=models.BooleanField(default=False, verbose_name='aprovada'),
        ),
        migrations.RunPython(set_existing_skills_approved, migrations.RunPython.noop),
    ]
