# Generated by Django 6.0.3 on 2026-03-13 10:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='email address')),
                ('telefone', models.CharField(max_length=20, unique=True, verbose_name='telefone')),
                ('nome', models.CharField(max_length=255, verbose_name='nome completo')),
                ('perfil', models.CharField(choices=[('JO', 'Jovem'), ('OP', 'Operador Distrital'), ('EMP', 'Empresa'), ('ADM', 'Administrador'), ('TEC', 'Técnico PNUD')], default='JO', max_length=3, verbose_name='perfil')),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_verified', models.BooleanField(default=False, verbose_name='verificado')),
                ('consentimento_dados', models.BooleanField(default=False, help_text='Autorizo o uso dos meus dados para fins de empregabilidade', verbose_name='consentimento para uso de dados')),
                ('consentimento_contacto', models.BooleanField(default=False, help_text='Autorizo ser contactado por SMS/WhatsApp/email', verbose_name='consentimento para contacto')),
                ('data_consentimento', models.DateTimeField(blank=True, null=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nome_empresa', models.CharField(blank=True, max_length=255, verbose_name='nome da empresa')),
                ('nif', models.CharField(blank=True, max_length=20, verbose_name='NIF')),
                ('setor_empresa', models.CharField(blank=True, max_length=100, verbose_name='setor')),
                ('associacao_parceira', models.CharField(blank=True, max_length=255, verbose_name='associação/parceiro')),
            ],
            options={
                'verbose_name': 'utilizador',
                'verbose_name_plural': 'utilizadores',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='PasswordResetCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, verbose_name='código')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'código de recuperação',
                'verbose_name_plural': 'códigos de recuperação',
            },
        ),
    ]
