# Generated by Django 6.0.3 on 2026-03-18 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_phonechange'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bi_numero',
            field=models.CharField(blank=True, max_length=50, verbose_name='número do BI'),
        ),
    ]
