# Generated by Django 5.0.7 on 2026-04-17 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_bi_numero'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityQuestionAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('failed_attempts', models.PositiveSmallIntegerField(default=0, verbose_name='tentativas falhadas')),
                ('blocked_until', models.DateTimeField(blank=True, null=True, verbose_name='bloqueado até')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='security_question_attempt', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'tentativa de perguntas de segurança',
                'verbose_name_plural': 'tentativas de perguntas de segurança',
            },
        ),
        migrations.CreateModel(
            name='SecurityQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_key', models.CharField(choices=[('mother_second_name', 'Qual é o segundo nome da tua mãe?'), ('father_second_name', 'Qual é o segundo nome do teu pai?'), ('favorite_pet_name', 'Qual é o nome do teu animal preferido?'), ('grandparent_name', 'Qual é o nome do teu avô ou avó?'), ('favorite_dish', 'Qual é o teu prato favorito?')], max_length=50, verbose_name='pergunta')),
                ('answer_hash', models.CharField(max_length=128, verbose_name='resposta criptografada')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='ordem')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_questions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'pergunta de segurança',
                'verbose_name_plural': 'perguntas de segurança',
                'ordering': ['user', 'order'],
                'unique_together': {('user', 'question_key')},
            },
        ),
    ]
