# Generated by Django 6.0.3 on 2026-03-13 10:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='nome da empresa')),
                ('nif', models.CharField(blank=True, max_length=20, verbose_name='NIF')),
                ('setor', models.CharField(choices=[('AGR', 'Agricultura'), ('TUR', 'Turismo'), ('TIC', 'Tecnologias de Informação'), ('IND', 'Indústria'), ('SER', 'Serviços'), ('ENE', 'Energias Renováveis'), ('ADM', 'Administração Pública'), ('SAU', 'Saúde'), ('EDU', 'Educação'), ('CON', 'Construção'), ('COM', 'Comércio'), ('FIN', 'Financeiro'), ('OUT', 'Outro')], max_length=3, verbose_name='setor de atividade')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('website', models.URLField(blank=True, verbose_name='website')),
                ('endereco', models.TextField(blank=True, verbose_name='endereço')),
                ('ativa', models.BooleanField(default=True, verbose_name='ativa')),
                ('verificada', models.BooleanField(default=False, verbose_name='verificada')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='registada em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizada em')),
                ('distrito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.district', verbose_name='distrito')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_profile', to=settings.AUTH_USER_MODEL, verbose_name='utilizador')),
            ],
            options={
                'verbose_name': 'empresa',
                'verbose_name_plural': 'empresas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField(verbose_name='motivo do contacto')),
                ('estado', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado')], default='PENDENTE', max_length=10, verbose_name='estado')),
                ('resposta_admin', models.TextField(blank=True, verbose_name='resposta do admin')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='solicitado em')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='respondido em')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_requests', to='companies.company', verbose_name='empresa')),
                ('youth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_requests', to='profiles.youthprofile', verbose_name='jovem')),
            ],
            options={
                'verbose_name': 'pedido de contacto',
                'verbose_name_plural': 'pedidos de contacto',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='título')),
                ('descricao', models.TextField(verbose_name='descrição')),
                ('requisitos', models.TextField(verbose_name='requisitos')),
                ('tipo', models.CharField(choices=[('EST', 'Estágio'), ('EMP', 'Emprego'), ('FOR', 'Formação')], max_length=3, verbose_name='tipo')),
                ('local_trabalho', models.CharField(blank=True, max_length=255, verbose_name='local de trabalho')),
                ('nivel_educacao', models.CharField(blank=True, choices=[('BAS', 'Básico'), ('SEC', 'Secundário'), ('TEC', 'Técnico'), ('SUP', 'Superior')], max_length=3, verbose_name='nível de educação requerido')),
                ('area_formacao', models.CharField(blank=True, choices=[('AGR', 'Agricultura'), ('TUR', 'Turismo'), ('TIC', 'Tecnologias de Informação'), ('IND', 'Indústria'), ('SER', 'Serviços'), ('ENE', 'Energias Renováveis'), ('ADM', 'Administração'), ('SAU', 'Saúde'), ('EDU', 'Educação'), ('CON', 'Construção'), ('ELE', 'Eletricidade'), ('CAN', 'Canalização'), ('INF', 'Informática'), ('OUT', 'Outra')], max_length=3, verbose_name='área de formação')),
                ('experiencia_minima', models.IntegerField(default=0, verbose_name='experiência mínima (anos)')),
                ('salario', models.CharField(blank=True, max_length=255, verbose_name='salário/remuneração')),
                ('beneficios', models.TextField(blank=True, verbose_name='benefícios')),
                ('estado', models.CharField(choices=[('ATIVA', 'Ativa'), ('FECHADA', 'Fechada'), ('PAUSADA', 'Pausada')], default='ATIVA', max_length=10, verbose_name='estado')),
                ('data_publicacao', models.DateTimeField(auto_now_add=True, verbose_name='publicada em')),
                ('data_fecho', models.DateField(blank=True, null=True, verbose_name='data de fecho')),
                ('visualizacoes', models.PositiveIntegerField(default=0, verbose_name='visualizações')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_posts', to='companies.company', verbose_name='empresa')),
                ('distrito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.district', verbose_name='distrito')),
            ],
            options={
                'verbose_name': 'vaga',
                'verbose_name_plural': 'vagas',
                'ordering': ['-data_publicacao'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_ANALISE', 'Em Análise'), ('ACEITE', 'Aceite'), ('REJEITADA', 'Rejeitada')], default='PENDENTE', max_length=15, verbose_name='estado')),
                ('mensagem', models.TextField(blank=True, verbose_name='mensagem/motivação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='candidatou-se em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('youth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='profiles.youthprofile', verbose_name='jovem')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='companies.jobpost', verbose_name='vaga')),
            ],
            options={
                'verbose_name': 'candidatura',
                'verbose_name_plural': 'candidaturas',
                'ordering': ['-created_at'],
                'unique_together': {('job', 'youth')},
            },
        ),
    ]
