# Generated by Codex on 2026-03-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='resposta_empresa',
            field=models.TextField(blank=True, verbose_name='mensagem da empresa'),
        ),
    ]
