# Generated by Django 6.0.3 on 2026-03-17 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_application_resposta_empresa'),
        ('companies', '0002_company_logo'),
    ]

    operations = [
    ]
