# Generated by Codex on 2026-03-17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_merge_20260317_1853'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('EMP', 'Empresa'), ('SYS', 'Sistema')], default='EMP', max_length=3, verbose_name='remetente')),
                ('message', models.TextField(verbose_name='mensagem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='enviada em')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='companies.application', verbose_name='candidatura')),
            ],
            options={
                'verbose_name': 'mensagem de candidatura',
                'verbose_name_plural': 'mensagens de candidatura',
                'ordering': ['-created_at'],
            },
        ),
    ]
