# Generated by Codex on 2026-03-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_application_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='numero_vagas',
            field=models.PositiveIntegerField(default=1, verbose_name='número de vagas'),
        ),
    ]
